### ISSUE TITLE
update CLI documents not to reference "uatom" or fractional tokens

### ISSUE THREAD

**Issue by hydrogen18** [akash-network/node#1054]
We have at least 1 CLI flag that as a docstring with an example of `0.1uatom`. Example should be in our token `uakt`. We don't allow fractional `uakt`. This is coming from Cosmos so we'll want to overwrite things most likely so the help looks OK, then submit a PR to them that might be able to fix this.

**Comment by boz** [comment]
The `--gas-prices` argument can use fractional tokens.  They use an `sdk.DecCoin` instead of an `sdk.Coin` - the underlying amount is a decimal not an integer.
