### ISSUE TITLE
unable to specify output format for `akash tx create` subcommands

### ISSUE THREAD

**Issue by gosuri** [akash-network/node#1271]
`akash tx create` is missing `-o` flag unlike rest of the commands. The output format should be consistent across all commands.

**Comment by hydrogen18** [comment]
I think this is a cosmos SDK thing. For example osmosis has the same missing flag on all its `tx` commands.

I'd need to double check but I think it has to do with the fact that `--generate-only` dumps a transaction to standard out in a predetermined format. Choosing a different format would give you a signed transaction that couldn't be fed into anything else.
