### ISSUE TITLE
Error: error unmarshalling: unexpected end of JSON input

### ISSUE THREAD

**Issue by sarasioux** [akash-network/node#1282]
### Issue type

Bug

### Akash version

v0.12.2-rc4

### Akash token balance

19480788

### What happened
I sporadically receive the error "unmarshalling: unexpected end of JSON input" when running commands like market bid list or market lease list.  I suspect it might be throttling me, but without a helpful error message it is impossible to know.

### What did you expect to happen

A helpful error message letting me know what went wrong.

### How to reproduce it

  It is very difficult to reproduce reliably, but here are some clues:
* Seems to happen more when I'm running a lot of commands quickly in succession (using an API)
* Seems to happen more on some nodes than others
* Seems to only happen on "list" commands

### Environment

mainnet
Mac OS

### Anything else we need to know?

I'm working on the Akash UI bounty and I'm hitting the command line via an API wrapper, so I'm pretty confident it's some sort of throttling mechanism, possibly intentional possibly not.

## Next steps

You may [join developer chat](https://akash.network/chat) for community support.

**Comment by hydrogen18** [comment]
Hello @sarasioux  this is an issue with the RPC node we think. Can you confirm what RPC node you are using? It would be set via `AKASH_NODE` or using the `--node` flag when you run `akash`
