### ISSUE TITLE
make clean target doesn't clean the kind cluster.

### ISSUE THREAD

**Issue by arijitAD** [akash-network/node#1312]
The cluster started with `make kind-cluster-create` isn't fully deleted by `make clean kind-cluster-clean`. i.e., these set of steps will give an error:
    * `make kind-cluster-create`
    * `make clean kind-cluster-clean`
    * `make kind-cluster-create`
    Need to manually delete it with `kind delete cluster --name single`
Source: https://github.com/ovrclk/akash/tree/master/_run/single

Solution:
1. Either add the code to delete the cluster in make target
2. Update the documentation to manually clean the cluster.

**Comment by hydrogen18** [comment]
I believe I used `make kind-cluster-delete` to remove the created cluster. Maybe the `kind-cluster-clearn` target should be updated to run that?

**Comment by boz** [comment]
`kind-cluster-clean` originally deleted everything that the provider created *in kubernetes* - it **cleaned** the **cluster**, maybe `kind-cluster-reset` would be better because `*clean` is so often used for deleting files?
