### ISSUE TITLE
provider: reservation not found after reboot

### ISSUE THREAD

**Issue by boz** [akash-network/node#1462]
After rebooting or possibly more (@sacreman will have more details), my deployment pod is running and up, but there is no `providerhosts` for it and when I re-send the manifest, this is in the logs:

```
E[2021-11-23|15:52:25.461] error looking up manifest                    module=provider-cluster cmp=service err="reservation not found" lease=akash1apchhdvxn7u7tpnfv7c6pnhcdc7kjhcw5sz0zm/10/1/1/akash1q7spv2cw06yszgfp4f9ed59lkka6ytn8g4tkjf group-name=main
```

I believe that this is preventing me from getting an ingress for my lease.

version: `0.14.1-rc8`

**Comment by hydrogen18** [comment]
is this still an issue?
