### ISSUE TITLE
akash client to report a version mismatch between the client & server

### ISSUE THREAD

**Issue by arno01** [akash-network/node#1558]
Akash client should report whenever there is a version mismatch between the client & server.

As the providers will be getting upgraded to newer versions (0.16 soon), some clients who are still running 0.14.1 (or older) will keep getting errors without a hint on what is the problem.
As well as some providers won't keep up with upgrading their Akash version to the latest one.

I've already seen some users were asking questions about the errors they were getting from the client because they were using too old Akash client (i.e. v0.12)

**Comment by hydrogen18** [comment]
We had discussed this but I don't think it has been implemented yet

**Comment by boz** [comment]
We actually have the `/version` endpoint: https://github.com/ovrclk/akash/blob/1ab8ee6ebd1321d98fb899c8661316cf182a4d4d/provider/gateway/rest/router.go#L95-L99

**Comment by arno01** [comment]
Just for the record:

```
$ curl -sk https://provider.akash.pro:8443/version | jq 
{
  "akash": {
    "version": "v0.16.3",
    "commit": "1d18f43bc415b37197e332f836dfcd7506766c3b",
    "buildTags": "\"osusergo,netgo,ledger,static_build\"",
    "go": "go version go1.17.6 linux/amd64",
    "cosmosSdkVersion": "v0.45.1"
  },
  "kube": {
    "major": "1",
    "minor": "22",
    "gitVersion": "v1.22.7+k3s1",
    "gitCommit": "8432d7f239676dfe8f748c0c2a3fabf8cf40a826",
    "gitTreeState": "clean",
    "buildDate": "2022-02-24T23:03:47Z",
    "goVersion": "go1.16.10",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```
