### ISSUE TITLE
akash validate-genesis fails after 0.16.3 upgrade

### ISSUE THREAD

**Issue by arno01** [akash-network/node#1565]
```
~/.akash/config$ akash validate-genesis
and get the following => Error: error validating genesis file    /home/ubuntu/.akash/config/genesis.json: failed to unmarshal authz genesis state: EOF
```

Ref. https://discord.com/channels/747885925232672829/751246770885099533/969096619255545896

and in my case as well:

```
# akash validate-genesis
Error: error validating genesis file /root/.akash/config/genesis.json: failed to unmarshal authz genesis state: EOF

# akash version
v0.16.3

# sha256sum /root/.akash/config/genesis.json
e15a7a57f856f602a8ebce131df453db047b3d4d3abaa00b44b821384b9c9726  /root/.akash/config/genesis.json
```

**Comment by hydrogen18** [comment]
I got this 

```
$ ~/akash_0.16.3_linux_amd64/akash validate-genesis ./genesis.json.1 
Error: error validating genesis file ./genesis.json.1: MaxExpectedTimePerBlock cannot be zero
```

**Comment by boz** [comment]
it's probably a new field that isn't in our genesis.

**Comment by troian** [comment]
is it on a freshly generated genesis via `akash init` or current mainnet?

**Comment by arno01** [comment]
> is it on a freshly generated genesis via `akash init` or current mainnet?

current mainnet.
Haven't checked the freshly generated genesis.

**Comment by arno01** [comment]
(just guessing)
Could it be that `genesis.json` needs to be exported so to contain the `authz` & `inflation` there sinec https://github.com/ovrclk/akash/blob/v0.16.3/app/app.go#L496 ?

Similarly to like we've been [hard forking](https://github.com/ovrclk/docs/blob/4474c91960b2eaa112bb57e5ea35fc6a1f2b08b2/guides/upgrade-mainnet.md) before when were getting from `0.8.3` -> `0.10.1`
