### ISSUE TITLE
potential pruning fix for v0.18

### ISSUE THREAD

**Issue by boz** [akash-network/node#1718]
During the upgrade to `v0.18.x` it was found that we needed to set `prune=nothing` for there to be a consistent state.

Simo from @activenodes suggests a possible solution:

> Hei Adam, about pruning= it could be something like this: https://github.com/cosmos/ibc-go/issues/1088#issuecomment-1062875169
> Usually that error comes up if in the chain code a store key hasn't been deleted/added correctly.
> This is what the Desmos team (Riccardo) suggested to me that we first came across many months ago
> In the code:
> 1. The following keys have been added here: https://github.com/ovrclk/akash/blob/1324f29f656b6aba28e34af982c2ae8842fe863b/app/config.go#L109
> icacontrollertypes.StoreKey,
> icaauthtypes.StoreKey,
> icahosttypes.StoreKey,

> 2. Within the upgrade code, only the following keys have been entered here: https://github.com/ovrclk/akash/blob/v0.18.0/app/app.go#L598
> icacontrollertypes.StoreKey, icahosttypes.StoreKey

> There is a key (icaauthtypes.StoreKey,) which was not entered during the upgrade 
> Maybe it will take another update

**Comment by troian** [comment]
fixed in `v0.20.0`
