### ISSUE TITLE
chore: address all todo

### ISSUE THREAD

**Issue by troian** [akash-network/node#791]
currently there are 60 `todo` items and it is good to start tracking them as issues.
also when creating new `todo` or `fixme` new it should have reference to either new or existing issue
for example `todo (#788) bla bla`

![image](https://user-images.githubusercontent.com/2477474/91462502-3d36f780-e858-11ea-8af5-13a96ed083b2.jpeg)

**Comment by troian** [comment]
also adding github-action to parse commit and check new todos matching regexp like this
`^\s*// (todo|TODO|fixme|FIXME) \(#\d+\)\s\w+`

@boz @Ropes thoughts?

**Comment by Ropes** [comment]
Would the Github Action only detect new TODO's or would it also flag all existing ones?

**Comment by troian** [comment]
depends how check is implemented. there can be either commit check which is definitely faster as less code to check or through entire code base.
i think we should go 1st option but fix all existing todo

**Comment by troian** [comment]
actions example https://github.com/marketplace/actions/todo-actions
