### ISSUE TITLE
Come up with a way for us to call Cosmos AddTxFlagsToCmd without mandatory CLI flags

### ISSUE THREAD

**Issue by hydrogen18** [akash-network/node#908]
Cosmos exposes a function `AddTxFlagsToCmd` to add some flags to a cobra command object 

https://github.com/cosmos/cosmos-sdk/blob/v0.40.0-rc3/client/flags/flags.go#L87

The problem is they are doing  `cmd.MarkFlagRequired(FlagChainID) `. This means that a user absolutely must provide `--chain-id` on the command line when it runs. There is no way around this that I could find. In Akash we want users to be able to specify all configuration via whatever means they want (configuration file, env. var, etc.). Also most end users aren't going to be changing chain ID very often so requiring this is not a very good idea.

We need to patch Cosmos SDK to allow us to get the same flags added to the command but without the mandatory requirement. Once we have gotten that patch into Cosmos SDK we need to update to a version that contains the patch.

**Comment by boz** [comment]
Maybe we can set a default value on that flag?

**Comment by boz** [comment]
Maybe we can overwrite what `MarkFlagRequired()` does?

```go
// MarkFlagRequired instructs the various shell completion implementations to
// prioritize the named flag when performing completion,
// and causes your command to report an error if invoked without the flag.
func MarkFlagRequired(flags *pflag.FlagSet, name string) error {
	return flags.SetAnnotation(name, BashCompOneRequiredFlag, []string{"true"})
}
```
Or even just unroll the entire `AddTxFlagsToCmd` and skip the `MarkFlagRequired`.

**Comment by hydrogen18** [comment]
Yeah, I think either one of those would work. If this isn't high priority I'd prefer to just propose a patch to cosmos SDK first that allows us to opt out of this.
