### ISSUE TITLE
cluster: support v1beta1 ingress by migrating to k8s operator

### ISSUE THREAD

**Issue by boz** [akash-network/node#960]
We now do not support k3sup because k3sup does not support the newer v1 Ingress objects.

I think this would be a good time to start migrating `provider/cluster/kube` code into independent k8s operators. 
 We can have two flavors of the ingress-generating operator - one for v1beta1 Ingress, and one for v1 Ingress.

The operator would watch for saved manifests and create ingress objects off of that.  The builder code in `provider/cluster/kube` would no longer need to create the ingresses.

**Comment by troian** [comment]
we probably should check version of kubernets on provider start and return error if it is not supported

**Comment by hydrogen18** [comment]
We discussed this a while back and basically it can be summed up as 

1. Yes we can support the v1beta1 ingress type
2. This is a decent amount of engineering effort
3. It basically doubles the amount of tests we need to do around ingress configuration
4. This would basically just be to support k3s? I can't imagine any real provider wanting us to use k3s. It's fun for toy projects and stuff but I can't see why we'd need to support it.
